# Generated by Django 5.0.4 on 2024-04-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_appointment_appointmenttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='compounder',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='compounder',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
