# Generated by Django 5.0.4 on 2024-04-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_compounder_password_compounder_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='compounder',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
