# Generated by Django 5.0.4 on 2024-04-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_appointment_id_alter_compounder_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='p_date',
        ),
    ]
