# Generated by Django 5.0.4 on 2024-04-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
