# Generated by Django 5.0.4 on 2024-04-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_remove_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compounder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='compounder',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='compounder',
            name='last_name',
        ),
    ]
