# Generated by Django 5.0.4 on 2024-04-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_remove_compounder_email_remove_compounder_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compounder',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='compounder',
            name='first_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='compounder',
            name='last_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
