# Generated by Django 5.0.4 on 2024-04-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_compounder_email_compounder_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.CharField(choices=[('', '-------- Select symptom --------'), ('Fever', 'Fever'), ('Cough', 'Cough'), ('Headache', 'Headache'), ('Fatigue', 'Fatigue'), ('Shortness of breath', 'Shortness of breath'), ('Other', 'Other')], max_length=100),
        ),
    ]
