# Generated by Django 5.0.4 on 2024-04-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_medicine_created_at_alter_patient_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='compounder',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
