# Generated by Django 5.0.4 on 2024-04-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_compounder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='a_note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
