# Generated by Django 5.0.4 on 2024-04-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_medicine_barcode_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='barcode_value',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
