# Generated by Django 3.0.5 on 2024-04-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_compounder_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.CharField(choices=[('Fever', 'Fever'), ('Cough', 'Cough'), ('Headache', 'Headache'), ('Fatigue', 'Fatigue'), ('Shortness of breath', 'Shortness of breath'), ('Other', 'Other')], max_length=100),
        ),
    ]
