# Generated by Django 5.0.4 on 2024-04-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_alter_medicine_barcode_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='add_note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
