# Generated by Django 5.0.4 on 2024-04-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_appointment_add_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='serial_number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.CharField(choices=[('', '-------- Select diagnosis --------'), ('Fever', 'Fever'), ('Cough', 'Cough'), ('Headache', 'Headache'), ('Fatigue', 'Fatigue'), ('Shortness of breath', 'Shortness of breath'), ('Other', 'Other')], max_length=100),
        ),
    ]
