# Generated by Django 5.0.2 on 2024-04-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_auto_20240405_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='compounder',
            name='first_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='compounder',
            name='last_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
