# Generated by Django 5.0.4 on 2024-04-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_alter_appointment_appointmentdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='staff_note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
