# Generated by Django 3.0.5 on 2024-04-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_auto_20240409_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assignedDoctorId',
        ),
    ]
