# Generated by Django 3.0.5 on 2024-04-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_auto_20240409_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('compounder', 'Compounder')], max_length=10),
        ),
    ]
