# Generated by Django 3.0.5 on 2024-04-09 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0029_auto_20240409_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compounder',
            name='user',
        ),
        migrations.AddField(
            model_name='compounder',
            name='doctor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.Doctor'),
        ),
    ]
