# Generated by Django 5.0.4 on 2024-04-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0032_appointment_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='staff_check_medicine',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
